#!/bin/zsh

figlet -f larry3d `hostname -s`

echo ""
if fortune futurama &> /dev/null; then
  fortune futurama
else
  fortune startrek
fi
echo ""

setopt auto_cd
setopt multios
setopt cdablevars

setopt prompt_subst
autoload -U promptinit
promptinit
prompt railsbros
