#!/bin/zsh

export LC_CTYPE=en_US.UTF-8

if [ -f /usr/local/bin/gdircolors ]; then
  if test -x =gdircolors; then
      eval "`gdircolors ~/.zsh.d/dircolors`"
      export LS_COLORS="*.ogm=01;35:${LS_COLORS}"
      export ZLS_COLORS=$LS_COLORS
  fi
else
  if test -x =dircolors; then
      eval "`dircolors ~/.zsh.d/dircolors`"
      export LS_COLORS="*.ogm=01;35:${LS_COLORS}"
      export ZLS_COLORS=$LS_COLORS
  fi
fi

# zmv "programmable rename"
autoload -U zmv

autoload -U is-at-least

is-at-least 4.3.0 && {
  unsetopt hist_save_by_copy
}

# http://xanana.ucsc.edu/~wgscott/wordpress_new/wordpress/?p=12
typeset -ga preexec_functions
typeset -ga precmd_functions
typeset -ga chpwd_functions

[ -w $zsh_cache ] && HISTFILE=$zsh_cache/history

HISTSIZE=10000              # size of history
LISTMAX=1000                # never ask
NULLCMD='cat'               # use cat for > null commands
REPORTTIME=2                # report time if execution exceeds amount of seconds
SAVEHIST=10000              # maximum of history events to be save
LOGCHECK=60
watch=(notme)               # watch login/logout

setopt auto_name_dirs
setopt auto_pushd               # make cd push the dir to a stack
setopt pushd_ignore_dups        # Don't push the same dir twice
DIRSTACKSIZE=10                 # Max. size of the stack befor it gets truncated

setopt appendhistory autocd extendedglob hist_ignore_all_dups share_history inc_append_history hist_ignore_space

## smart urls
autoload -U url-quote-magic
zle -N self-insert url-quote-magic

## jobs
setopt long_list_jobs

## pager
export PAGER=less
export LC_CTYPE=en_US.UTF-8

autoload -U select-word-style
select-word-style bash
