#!/bin/zsh

bindkey -e '^[[3~' delete-char
# bindkey -v "^[Od" backward-word
# bindkey -v "^[Oc" forward-word

bindkey -e "^A" beginning-of-line
bindkey -e "^E" end-of-line
bindkey -e "^K" kill-line
bindkey -e "^L" clear-screen
bindkey -e "^U" kill-whole-line
bindkey -e "^V" quoted-insert
bindkey -e "^W" backward-kill-word

bindkey -e "^N" down-history
bindkey -e "^P" up-history

bindkey -e "^[H" run-help
bindkey -e "^[h" run-help

# alow for editing of the command line
# http://zshwiki.org/home/examples/zlewidgets
autoload -U    edit-command-line
zle -N         edit-command-line
bindkey -a 'v' edit-command-line

# vi editing
bindkey -e

bindkey '^r' history-incremental-search-backward
bindkey '^f' history-incremental-search-forward
