#!/bin/zsh

# emacs editing
bindkey -e

bindkey -e '^[[3~' delete-char

bindkey -e "^A" beginning-of-line
bindkey -e "^E" end-of-line
bindkey -e "^K" kill-line
bindkey -e "^L" clear-screen
bindkey -e "^U" kill-whole-line
bindkey -e "^V" quoted-insert
bindkey -e "^W" backward-kill-word

bindkey -e "^N" down-history
bindkey -e "^P" up-history

## file rename magick
bindkey "^m" copy-prev-shell-word
#
# alow for editing of the command line
# http://zshwiki.org/home/examples/zlewidgets
autoload -U    edit-command-line
zle -N         edit-command-line
bindkey '\ee'  edit-command-line

bindkey '^r' history-incremental-search-backward
bindkey '^f' history-incremental-search-forward
