#!/bin/zsh

figlet -f larry3d `hostname -s`

echo ""
if fortune futurama &> /dev/null; then
  fortune futurama
else
  fortune startrek
fi
echo ""

setopt AUTO_CD
setopt MULTIOS
setopt CDABLEVARS

setopt PROMPT_SUBST

autoload -U promptinit
promptinit
prompt railsbros
