#!/bin/zsh

if [[ -f ~/.dotfiles/logo.ascii ]]; then
  cat ~/.dotfiles/logo.ascii
else
  figlet -f larry3d `hostname -s`
fi

echo ""
if fortune futurama &> /dev/null; then
  fortune futurama
else
  fortune startrek
fi
echo ""

autoload -U promptinit
promptinit
prompt railsbros
