fpath=(~/.zsh.d/custom_funcs $fpath)
typeset -U fpath

autoload -U compinit
compinit

autoload -U tetris
zle -N tetris
bindkey ^T tetris

if [ `uname` = 'Darwin' ]; then
  export VISUAL='mvim -f -c "au VimLeave * !open -a $TERM_PROGRAM"'
  export EDITOR='mvim -f -c "au VimLeave * !open -a $TERM_PROGRAM"'
else
  export VISUAL="vim"
  export EDITOR='vim'
fi

