#! /bin/zsh

setopt extended_glob

# load specific configurations
for zshrc_snipplet in ~/.zsh.d/C[0-9][0-9]*[^~] ; do
  source $zshrc_snipplet
done

# custom configs are taken from this file
if [ -f ~/.zsh_config_for_`whoami` ]; then
  source ~/.zsh_config_for_`whoami`
fi
