#! /bin/zsh

export LC_ALL="en_US.UTF-8"

if [[ -f $HOME/.zsh.d/base16-pinkiepie.dark.sh ]]; then
  source $HOME/.zsh.d/base16-pinkiepie.dark.sh
fi

if [[ -d $HOME/.rvm/bin ]]; then
  PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
fi

# Add custom completions and prompt to fpath
fpath=(~/.zsh.d/custom_funcs $fpath)

# Always use the coreutils if present
if [[ -d /usr/local/opt/coreutils/libexec/gnubin ]]; then
  PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
fi

# Load zshuery
source ${HOME}/.zshuery/zshuery.sh
load_defaults
load_aliases

setopt extended_glob

# Configure colors
if [[ -x dircolors ]]; then
  eval "`dircolors ~/.zsh.d/dircolors`"
  export ZLS_COLORS=$LS_COLORS
fi

# Configure completion
if [[ -d /usr/local/share/zsh-completions ]]; then
  load_completion /usr/local/share/zsh-completions
else
  load_completion ${HOME}/.zshuery/completion
fi

# Setup editor
export VISUAL='vim'
export EDITOR='vim'

# Use another histfile
[ -w $zsh_cache ] && HISTFILE=$zsh_cache/history

# Set options
setopt path_dirs
setopt auto_pushd               # make cd push the dir to a stack
setopt long_list_jobs
autoload -U is-at-least
is-at-least 4.3.0 && {
  unsetopt hist_save_by_copy
}

LISTMAX=1000                # never ask
NULLCMD='cat'               # use cat for > null commands
REPORTTIME=2                # report time if execution exceeds amount of seconds
LOGCHECK=60
watch=(notme)               # watch login/logout
DIRSTACKSIZE=10                 # Max. size of the stack befor it gets truncated

## Setup the default pager
export PAGER=less
export LESS="-X"

# http://xanana.ucsc.edu/~wgscott/wordpress_new/wordpress/?p=12
typeset -ga preexec_functions
typeset -ga precmd_functions
typeset -ga chpwd_functions

autoload -U select-word-style
select-word-style bash

# load specific configurations
plugins=(zsh-syntax-highlighting zsh-history-substring-search)
for zshrc_snipplet in ~/.zsh.d/C[0-9][0-9]*[^~] ; do
  source $zshrc_snipplet
done

# custom configs are taken from this file
if [ -f ~/.zsh_config_for_`whoami` ]; then
  source ~/.zsh_config_for_`whoami`
fi
